#! /bin/bash

set -e
set -x

mv /usr/sbin/policy-rc.d.disabled /usr/sbin/policy-rc.d
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install \
	ca-certificates \
	curl \
	wget
mkdir /build
wget -O /build/setup_12.x https://deb.nodesource.com/setup_12.x
chmod a+x /build/setup_12.x
/build/setup_12.x

DEBIAN_FRONTEND=noninteractive apt-get -y --no-install-recommends install \
	build-essential \
	ffmpeg \
	git \
	libgif-dev \
	nodejs \
	python2.7

apt-get -y -u dist-upgrade
apt-get clean
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

git clone https://gitlab.com/Shinobi-Systems/Shinobi.git /opt/shinobi

cd /opt/shinobi

npm i npm@latest -g
npm install pg
npm install --unsafe-perm
npm audit fix --force

cd plugins/tensorflow

npm uninstall @tensorflow/tfjs-node-gpu --unsafe-perm
npm uninstall @tensorflow/tfjs-node --unsafe-perm
npm install yarn -g --unsafe-perm --force
npm install @tensorflow/tfjs-node-gpu@1.7.3 --unsafe-perm

cd node_modules/@tensorflow/tfjs-node-gpu

echo '{"tf-lib": "https://cdn.shinobi.video/installers/libtensorflow-gpu-linux-arm64-1.15.0.tar.gz"}' > "scripts/custom-binary.json"
npm install --unsafe-perm
npm audit fix --force

cd ../../..

npm install --unsafe-perm

systemctl enable x-tensorflow.js.service

/usr/local/bin/docker-wipelogs

mv /usr/sbin/policy-rc.d /usr/sbin/policy-rc.d.disabled
